config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
    resources :items, only: [:index, :show]
    post 'items/:id/add_to_cart', to: 'items#add_to_cart', as: 'add_to_cart'
    post "customers/confirm" => "customers#confirm"
    post "orders/confirm" => "orders#confirm"
    get "orders/thanks" => "orders#thanks"
    resources :orders, only: [:new, :index, :show, :create]
    get "customers/unsubscribe" => "customers#unsubscribe"
    resource :customers, only: [:show]
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    patch "customers/withdraw" => "customers#withdraw"
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resources :cart_items, only: [:index, :update, :destroy, :create] do
    delete :destroy_all, on: :collection
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  namespace :admin do
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get "/admin" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  has_one_attached :image
  
  def subtotal
    item.add_tax_sales_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true
  validates :email, presence: true

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{6,}+\z/
  

  validates :last_name, :first_name, presence: true, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/ }

  validates :last_name_kana, :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates_inclusion_of :is_active, in: [true, false]

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  attr_accessor :payment_method

  def name
    "#{last_name} #{first_name}"
  end
  
  def name_kana
  "#{last_name_kana} #{first_name_kana}"
  end
  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  belongs_to :genre

  has_one_attached :image

  def add_tax_sales_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details, dependent: :destroy

  has_one_attached :image

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum delivery_address: { my_address: 0, address: 1, new_address: 2 }

  def sum_of_order_price
    total_payment - shipping_cost
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    
def index
    @customers = Customer.page(params[:page]).per(10)
end

def show
    @customer = Customer.find(params[:id])
end

def edit
    @customer = Customer.find(params[:id])
end

def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "You have updated customer info successfully."
    else
      render :edit
    end
end
private

 def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
 end  

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "You have created genre successfully."
    else
      @genres = Genre.all
      render :index
    end
  end  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "You have updated genre successfully."
    else
      render :edit
    end
  end
  
   private

  def genre_params
    params.require(:genre).permit(:name)
  end  

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.includes(:order_details).page(params[:page]).per(10)
  end

  private

  def order_params
    params.require(:order).permit(:created_at, :name, :status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:amount)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
     redirect_to admin_item_path(@item.id)
    else
     render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.includes(:order_details).find(params[:id])
  end

  def update
   @order = Order.includes(:order_details).find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:name, :sipping_cost, :total_payment)
  end

  def order_detail_params
    params.require(:order_detail).permit(:price, :amount, :status)
  end

  def item_params
    params.require(:item).permit(:price)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
          <h4><%= @customer.name%>の会員情報編集</h4>
          <%= form_with model: @customer,url: admin_customer_path(@customer),local:true do |f| %>
          <table>
              <tr>
                <td>会員ID</td>
                <td><%= @customer.id %></td>
                  
              </tr>
              <tr>
                <td class="font-weight-bold">氏名 </td>
                <td><%= f.text_field :last_name, class: 'form-control last_name' %></td>
                <td><%= f.text_field :first_name, class: 'form-control first_name' %></td>
              </tr>
              <tr>
                  <td class="font-weight-bold">フリガナ </td>
                  <td>
                    <%= f.text_field :last_name_kana, class: 'form-control last_name_kana' %>
                    <%= f.text_field :first_name_kana, class: 'form-control first_name_kana' %> 
                  </td>
              </tr>
              <tr>
                  <td class="font-weight-bold">郵便番号 </td>
                  <td><%= f.number_field :postal_code, class: 'form-control postal_code' %></td>
              </tr>
              <tr>
                <td class="font-weight-bold">住所 </td>
                <td><%= f.text_field :address, class: 'form-control address' %></td>  
              </tr>
              <tr>
                <td class="font-weight-bold">電話番号 </td>
                <td><%= f.number_field :telephone_number, class: 'form-control telephone_number' %></td>
              </tr>
              <tr>
                <td class="font-weight-bold">メールアドレス </td>
                <td><%= f.text_field :email, class: 'form-control email' %></td>
              </tr>
              <tr>
                <td class="font-weight-bold">会員ステータス </td>
                <td class ="custom-control custom-radio custom-control-inline">
                 　<%= f.radio_button :is_active, true, checked: @customer.is_active == true, class: 'custom-control-input', id: 'status-active' %>
                   <%= f.label :is_active,'有効', class: 'custom-control-label', for: 'status-active' %>
                </td>   
                <td class ="custom-control custom-radio custom-control-inline"> 
                 <%= f.radio_button :is_active, false, checked: @customer.is_active == false, class: 'custom-control-input', id: 'status-deleted' %>
                  <%= f.label :is_active,'退会', class: 'custom-control-label', for: 'status-deleted' %>
                </td>
              </tr>
              <tr>
                <td><%= f.submit "変更を保存", class: "btn btn-primary" %></td>
              </tr>
          </table>
          <% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">  
    <div class="col">
      <h4 class="font-weight-bold ml-5">会員一覧</h4>
      <table class='table table-hover mx-auto my-5 w-75'>
        <thead class="bg-secondary ">
          <tr>
            <th class="font-weight-bold", style="width:100px">会員ID</th>
            <th class="font-weight-bold under"><u>氏名</u></th>
            <th class="font-weight-bold">メールアドレス</th>
            <th class="font-weight-bold">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %>
              </td>
              <td><%= link_to customer.name, admin_customer_path(customer) %></td>
              <td><%= customer.email %></td>
              <td class="<%= customer.is_active? ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %>"><%= customer.customer_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @customers %>
      </div>
    </div>  
  </div>  

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h4><%= @customer.name%>さんの会員詳細</h4>
            <table class="table table-borderless my-5 w-75"> 
                <tr>
                    <td class="font-weight-bold">会員id </td>
                    <td><%= @customer.id %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">氏名 </td>
                    <td><%= @customer.name %></td>
                </tr>
                <tr>
                     <td class="font-weight-bold">フリガナ </td>
                     <td><%= @customer.name_kana %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">郵便番号 </td>
                    <td><%= @customer.postal_code %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">住所 </td>
                    <td><%= @customer.address %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">電話番号 </td>
                    <td><%= @customer.telephone_number %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">メールアドレス </td>
                    <td><%= @customer.email %></td>
                </tr>  
                <tr>
                     <td class="font-weight-bold">会員ステータス </td>
                     <td class="<%= @customer.is_active? ? 'text-success font-weight-bold' : 'text-muted font-weight-bold' %> "><%= @customer.customer_status %></td>
                </tr> 
                <tr>
                    <td></td>
                    <td><%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success"%></td>
                    <td> <%= link_to "注文履歴一覧を見る", admin_admin_path, class: "btn btn-primary"%></td>
                </tr>
            </table>
        </div>
    </div>
</div>        
                  
              

app/views/admin/genres/_form.html.erb
<div class="from-items mb-5 mt-5">
<% if genre.new_record? %>
  <%= form_with model: genre,url: admin_genres_path, local:true do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :name, "ジャンル名", class:"font-weight-bold mr-4" %>
        <%= f.text_field :name, class: 'form-control genre_name ml-4 mr-4' %>
      </div>
      <div class="form-group">
        <%= f.submit genre.new_record? ? "新規投稿" : "変更を保存", class: "btn btn-success ml-4" %>
      </div>
     <% end %> 
    </div> 
 <% else %>
     <%= form_with model: genre,url: admin_genre_path, local:true do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :name, "ジャンル名", class:"font-weight-bold mr-4" %>
        <%= f.text_field :name, class: 'form-control genre_name ml-4 mr-4' %>
      </div>
      <div class="form-group">
        <%= f.submit genre.new_record? ? "新規投稿" : "変更を保存", class: "btn btn-success ml-4" %>
      </div>  
     <% end %> 
    </div>  
 <% end %> 
</div> 

app/views/admin/genres/_index.html.erb
<table class="table table-bordered table-sm w-25">
    <thead class="bg-secondary text-center">
        <tr>
            <th>ジャンル</th>
            <th colspan="1"></th>
        </tr>
    </thead>
    <tbody>
        <% genres.each do|genre|%>
        <tr>
            <td class="align-middle"><%= genre.name %></td>
            <td> <%= link_to "編集する", edit_admin_genre_path(genre.id),class: "btn btn-success w-75"%> </td>
        </tr>
        <% end %>
    </tbody>

</table>

app/views/admin/genres/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h4 class="mt-3">ジャンル編集</h4>
            <%= render "form", genre: @genre %>
        </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h4 class="mt-3">ジャンル一覧・追加</h4>
            <%= render "form", genre: @genre %>
            <%= render "index", genres: @genres %>
        </div>
    </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">  
    <div class="col">
      <h4 class="font-weight-bold">注文履歴一覧</h4>
      <table class="table table-hover mx-auto">
        <thead>
          <tr>
            <th class="font-weight-bold">購入日時</th>
            <th class="font-weight-bold">購入者</th>
            <th class="font-weight-bold">注文個数</th>
            <th class="font-weight-bold">注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do|order| %>
          <tr>
            <td>
               <%= link_to order.created_at.strftime('%Y-%m-%d %H:%M'), admin_order_path(order), class: 'text-primary' %>
            </td>
            <td><%= order.name %></td>
            <td><%= order.order_details.amount %></td>
            <td><%= order.status %></td>
          </tr>
        </tbody>
        <% end %>
      </table>    
      <%= paginate @orders %>
     </div>
    </div>  
  </div>        

app/views/admin/orders/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h4>注文履歴詳細</h4>
            <%= form_with model: @order do|f|%> 
            <table>
                <tr>    
                    <td class="font-weight-bold">購入者</td>
                    <td><%= link_to @order.name, admin_customer_path(@customer.id) %></td>
                </tr>
                <tr>
                     <td class="font-weight-bold">注文日</td>
                     <td><%= @order.created_at %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">配送先</td>
                    <td><%= @order.postal_code %><%= @order.address %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">支払方法</td>
                    <td><%= @order.payment_method %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">注文ステータス</td>
                    <td><%= f.collection_select :status, Order.all, :status, :status, {prompt: "入金待ち"}, class: 'form-control', id: 'genre-select' %></td>
                    <td><%= f.submit '更新' %></td>
                </tr>
            </table> 
            <table>
                <thead>
                    <tr>
                        <th class="font-weight-bold">商品名</th>
                        <th class="font-weight-bold">単価（税込）</th>
                        <th class="font-weight-bold">数量</th>
                        <th class="font-weight-bold">小計</th>
                        <th class="font-weight-bold">製作ステータス</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @order.order_details.each do |order_detail| %>
                    <tr>
                        <td><%= order_detail.item.name %></td>
                        <td><%= order_detail.add_tax_sales_price.to_s(:dalimited) %></td>
                        <td><%= order_detail.amount %></td>
                        <td><%= order_detail.price %></td>
                        <td><%= f.collection_select :making_status, Order_detail.all, :making_status, :making_status, {prompt: "着手不可"}, class: 'form-control', id: 'genre-select' %></td>
                        <td><%= f.submit '更新' %></td>
                    </tr>
                </tbody>
            </table>    
            <table>
                <tr>
                    <td class="font-weight-bold">商品合計</td>
                    <td> <%= @order.sum_of_order_price %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">送料</td>
                    <td><%= @order.shipping_cost %></td>
                </tr>
                <tr>
                    <td class="font-weight-bold">請求金額合計</td>
                    <td><%= @order.total_payment %></td>
                </tr>
            </table>    
                
                
                
               
                
                
               
                
                
                
                

app/views/publics/addresses/edit.html.erb
<h1>Public::Addresses#edit</h1>
<<<<<<< HEAD
<p>Find me in app/views/addresses/edit.html.erb</p>
=======
<p>Find me in app/views/public/addresses/edit.html.erb</p>
>>>>>>> develop

app/views/publics/addresses/index.html.erb
<h1>Public::Addresses#index</h1>
<<<<<<< HEAD
<p>Find me in app/views/addresses/index.html.erb</p>
=======
<p>Find me in app/views/public/addresses/index.html.erb</p>
>>>>>>> develop

app/views/publics/cart_items/index.html.erb
<h1>Public::CartItems#index</h1>
<<<<<<< HEAD
<p>Find me in app/views/cart_items/index.html.erb</p>
=======
<p>Find me in app/views/public/cart_items/index.html.erb</p>
>>>>>>> develop

app/views/publics/customers/edit.html.erb
<h1>Public::Customers#edit</h1>
<<<<<<< HEAD
<p>Find me in app/views/customers/edit.html.erb</p>
=======
<p>Find me in app/views/public/customers/edit.html.erb</p>
>>>>>>> develop

app/views/publics/customers/show.html.erb
<h1>Public::Customers#show</h1>
<<<<<<< HEAD
<p>Find me in app/views/customers/show.html.erb</p>
=======
<p>Find me in app/views/public/customers/show.html.erb</p>
>>>>>>> develop

app/views/publics/customers/unsubscribe.html.erb
<h1>Public::Customers#unsubscribe</h1>
<p>Find me in app/views/public/customers/unsubscribe.html.erb</p>

app/views/publics/customers/withdraw.html.erb
<h1>Public::Customers#withdraw</h1>
<p>Find me in app/views/customers/withdraw.html.erb</p>

app/views/publics/homes/about.html.erb
<div class="new-about text-center">
  <h1>About</h1>
  <p class="text-center">
    ながのCAKEは全国発送可能なケーキ屋さんです。<br>
    お子様からお年寄りの方までお召し上がりいただけるよう、<br>
    様々なバリエーションをご用意しております。<br>
    また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
    ぜひご注文ください。
  </p>
</div>

app/views/publics/homes/top.html.erb
<p>ジャンル検索</p>
genre_render

<p>
  ようこそ、ながのCAKEへ！<br>
  このサイトでは、ケーキ販売のECサイトになります。<br>
  会員でない方も商品の閲覧はできますが、<br>
  購入には会員登録が必要になります。
</p>

<h2>新着商品</h2>

<div>
  <div>
    画像
    <p><%= link_to "商品名", items_path %></p>
    <p>値段</p>
  </div>
</div>

<%= link_to items_path %>

app/views/publics/oders/comfirm.html.erb
<h1>Public::Oders#comfirm</h1>
<p>Find me in app/views/public/oders/comfirm.html.erb</p>

app/views/publics/oders/index.html.erb
<h1>Public::Oders#index</h1>
<p>Find me in app/views/public/oders/index.html.erb</p>

app/views/publics/oders/new.html.erb
<h1>Public::Oders#new</h1>
<p>Find me in app/views/public/oders/new.html.erb</p>

app/views/publics/oders/show.html.erb
<h1>Public::Oders#show</h1>
<p>Find me in app/views/public/oders/show.html.erb</p>

app/views/publics/oders/thanks.html.erb
<h1>Public::Oders#thanks</h1>
<p>Find me in app/views/public/oders/thanks.html.erb</p>